worker_processes auto;
events {
  worker_connections 1024;
}
http {
  # Wildcard cert created by certbot DNS challenge.
  # Expected files:
  # /etc/letsencrypt/live/jil.io.vn/fullchain.pem
  # /etc/letsencrypt/live/jil.io.vn/privkey.pem
  server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 301 https://ctf.jil.io.vn$request_uri;
  }
  # Configuration containing list of application servers
  upstream app_servers {
    server ctfd:8000;
  }
  server {
    listen 80;
    listen [::]:80;
    server_name ctf.jil.io.vn;
    return 301 https://$host$request_uri;
  }
  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ctf.jil.io.vn;
    ssl_certificate /etc/letsencrypt/live/jil.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jil.io.vn/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    gzip on;
    client_max_body_size 4G;
    # Handle Server Sent Events for Notifications
    location /events {
      proxy_pass http://app_servers;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
    }
    # Proxy connections to the application servers
    location / {
      proxy_pass http://app_servers;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
    }
  }
  upstream frps_servers {
    server frps:8009;
  }
  server {
    listen 80;
    listen [::]:80;
    server_name *.dynamic.jil.io.vn;
    client_max_body_size 4G;
    location / {
      proxy_pass http://frps_servers;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
    }
  }
}
